export const GET_NEW_FEED = 'GET_NEW_FEED';
export const CHANGE_SETTING = 'CHANGE_SETTING';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
