# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PhotoAwesome' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for PhotoAwesome
  #pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  #pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  #pod 'react-native-fetch-blob',
  # :path => '../node_modules/react-native-fetch-blob'
  pod 'AFNetworking', '~> 3.0'
  target 'PhotoAwesome-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'PhotoAwesomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PhotoAwesome-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoAwesome-tvOS
    inherit! :search_paths

end
